apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: todo-backend
          image: simurgan/todo-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: django-secret-key
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-pwd
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-port
            - name: GCP_KEY_PATH
              value: "secrets/gcp-key.json"
            - name: STORAGE_BUCKET_NAME
              value: "todo-cloud-bucket"
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
            - name: IS_DEBUG_MODE
              value: "False"
          volumeMounts:
            - name: gcp-key-volume
              mountPath: /app/secrets
              readOnly: true
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command:
            [
              "/cloud_sql_proxy",
              "-instances=$(INSTANCE_CONNECTION)=tcp:5432",
              "-credential_file=/secrets/cloudsql/gcp-key.json",
            ]
          env:
            - name: INSTANCE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: cloudsql-config
                  key: instance-connection
          volumeMounts:
            - name: gcp-key-volume
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: gcp-key-volume
          secret:
            secretName: django-secrets
            items:
              - key: gcp-key-json
                path: gcp-key.json
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
