apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: todo-backend
          image: simurgan/todo-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: GCP_KEY_PATH
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: GCP_KEY_PATH
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-pwd
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: db-port
          volumeMounts:
            - name: gcp-key-volume
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: gcp-key-volume
          secret:
            secretName: django-secrets
            items:
              - key: gcp-key-json
                path: gcp-key.json
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30200
