apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: todo-frontend
          image: simurgan/todo-frontend:latest
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "60Mi"
              cpu: "120m"
          env:
            - name: BACKEND_IP
              value: "<backend-url>" # change here after backend deploy and before frontend deploy
            - name: BACKEND_PORT
              value: "8000"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
