# Generated by Django 5.1.4 on 2024-12-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_todoitem_deadline_remove_todoitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='updated_at',
        ),
    ]
