# Generated by Django 5.1.4 on 2024-12-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_todoitem_order_remove_todoitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='todo-attachments/'),
        ),
    ]
